mod syncer;
use ethers::providers::Provider;
pub use syncer::*;
mod processor;
use crate::vault::Vault;
use ethers::prelude::Http;
use ethers::prelude::SignerMiddleware;
use ethers::signers::Wallet;
use k256::ecdsa::SigningKey;
pub use processor::*;
pub type VaultContract = Vault<SignerMiddleware<Provider<Http>, Wallet<SigningKey>>>;
