[package]
name = "hdeposit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.9"
anyhow = "1"
k256 = "0.13.1"
clap = {version = "4", features = ["derive"]}
tokio = {version = "1.32.0", features = ["full"]}
